import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

public class ScorePanel extends JPanel
{
    //Stores reference to the main GameFrame object.
    private GameFrame gameFrame;

    //Constructor for the Score Panel. Assigns the gameFrame variable a reference to the main GameFrame object passed.
    public ScorePanel(GameFrame gameFrame)
    {
        this.gameFrame = gameFrame;
    }

    /*Manipulates the Graphics object to draw Strings to the GUI.
     *These strings are of the all-time top 10, stored in an ArrayList, generated by the scores ScoresFile object.*/
    private void drawAllTop10(Graphics g)
    {
        //ArrayList contains the top 10 scores of all-time.
        ArrayList<Score> allTime10 = gameFrame.scores.getAllTimeTop10();
        //y represents the y coordinate the strings should be drawn at.
        int y = 20;
        //rank represents the rank of the score being drawn. Prefixed to the score before being drawn.
        int rank = 1;
        //String to represent the score as a string before being drawn. Is constructed in the following for loop.
        String entry;

        //Draws the title of the scores being drawn.
        g.drawString("      All Time Top 10:", 20, y);

        /*For each score in the top ten of all-time list. construct a string from the score, prefixed with its rank and
         *then draw it at the coordinates x=10, y=y.*/
        for(Score score : allTime10)
        {
            //Change y so the strings appear on top of one another.
            y += 20;
            //Construct the string to be drawn to include the rank, name and score achieved.
            entry = Integer.toString(rank) + ") Name: " + score.getName() + " || Score: " + score.getScore();
            g.drawString(entry, 10, y);
            rank++;
        }
    }

    /*Manipulates the Graphics object to draw Strings to the GUI.
     *These strings are of the recent top 10, stored in an ArrayList, generated by the scores ScoresFile object.*/
    private void drawRecentTop10(Graphics g)
    {
        //ArrayList contains the top 10 scores of the past 24 hours.
        ArrayList<Score> recentTop10 = gameFrame.scores.getRecentTop10();
        //y represents the y coordinate the strings should be drawn at.
        int y = 20;
        //rank represents the rank of the score being drawn. Prefixed to the score before being drawn.
        int rank = 1;
        //String to represent the score as a string before being drawn. Is constructed in the following for loop.
        String entry;

        //Draws the title of the scores being drawn.
        g.drawString("        Top 10 In Past 24 Hours:", 210, y);

        /*For each score in the recent top ten list. construct a string from the score, prefixed with its rank and
         *then draw it at the coordinates x=210, y=y.*/
        for(Score score : recentTop10)
        {
            //Change y so the strings appear on top of one another.
            y += 20;
            //Construct the string to be drawn to include the rank, name and score achieved.
            entry = Integer.toString(rank) + ") Name: " + score.getName() + " || Score: " + score.getScore();
            g.drawString(entry, 210, y);
            rank++;
        }
    }

    /*Manipulate the Graphics object to paint the recent and all-time top 10 scores to the GUI.
     *This is invoked whenever this panel is added to the GameFrame and when repaint() is invoked.*/
    @Override
    protected void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        drawAllTop10(g);
        drawRecentTop10(g);
    }

    //Override the preferred size method to return a new preferred size. Used when the GameFrame is packed (pack()).
    @Override
    public Dimension getPreferredSize(){return new Dimension(400, 400);}
}
